---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# FIESTAutils

The goal of `FIESTAutils` is to provide both general and specific functions for internal use for `FIESTA`, `FIESTAnalysis`, and the greater `FIESTA` ecosystem, along with providing some standalone tools to help enhance analyses for the advanced user. While these functions are generally meant to be used internally, one may be able to use them for their own analyses. Namely, we include functions for direct, model-assisted, and small area estimation, functions for raster analysis, functions for saving to different file types, and functions for spatial data analysis. 

Note: The `FIESTAutils` package is generally for internal use with `FIESTA` and `FIESTAnalysis`. While some functions may be useful on their own, they will not be regularly updated, documented, or changed for a particular use. 

## Installation

You can install the development version of FIESTAutils from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("USDAForestService/FIESTAutils")
```

We hope to soon have `FIESTAutils` available on CRAN. 